### ISSUE TITLE
Support remark-lint

### ISSUE THREAD

**Issue by sumyapp** [sider/runners#672]
## Support remark-lint
https://github.com/remarkjs/remark-lint
https://remark.js.org/

### Supplementary information

This issue is similar to these completed issues.

- cpplint support
  - https://github.com/sider/runners/pull/417
  - https://help.sider.review/tools/cplusplus/cpplint
- hadolint support
  - https://github.com/sider/runners/issues/581
  - https://github.com/sider/runners/pull/625
  - https://github.com/sider/sider-docs/pull/282

## TODO

- [ ] Write smoke test(with some linter's Option)
- [ ] Add pattern for success end, waring exit, error exit
- [ ] Add config option
- [ ] Add test for error exit
- [ ] Write document
- [ ] Add CI setting (https://github.com/sider/runners/blob/master/.circleci/config.yml)
- [ ] Discuss this Lint tool in this Issue
- [ ] Fix developer guide if needed (https://github.com/sider/runners#developer-guide)
