### ISSUE TITLE
Support SmartCPD

### ISSUE THREAD

**Issue by sumyapp** [sider/runners#699]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## Support [ANALYSIS_TOOL_NAME]

- Source code URL: [URL]
- Official Site/Documentation: [URL]

### Supplementary information

This issue is similar to these completed issues.

- cpplint support
  - https://github.com/sider/runners/pull/417
  - https://help.sider.review/tools/cplusplus/cpplint
- hadolint support
  - https://github.com/sider/runners/issues/581
  - https://github.com/sider/runners/pull/625
  - https://github.com/sider/sider-docs/pull/282

## TODO

- [ ] Write smoke test(with some linter's Option). Add pattern for success end, waring exit, error exit
- [ ] Add config option
- [ ] (Optional) Add unit tests for the new analysis tool's `Processor` if needed.
- [ ] Write documentation accordingly
- [ ] Add CI setting (https://github.com/sider/runners/blob/master/.circleci/config.yml)
- [ ] Discuss this Lint tool in this Issue
- [ ] Fix developer guide if needed (https://github.com/sider/runners#developer-guide)
