### ISSUE TITLE
Support detekt

### ISSUE THREAD

**Issue by gnakagaw** [sider/runners#704]
**Is your feature request related to a problem? Please describe.**
Support detekt (https://github.com/arturbosch/detekt)

**Describe the solution you'd like**
implementing a new runner for detekt

**Describe alternatives you've considered**
No alternatives

**Additional context**
Nothing

## Support [detekt]

- Source code URL: https://github.com/arturbosch/detekt
- Official Site/Documentation: https://arturbosch.github.io/detekt/

### Supplementary information

This issue is similar to these completed issues.

- ktlint support
  - https://github.com/sider/runners/pull/192
  - https://help.sider.review/tools/kotlin/ktlint

## TODO

- [ ] Write smoke test(with some linter's Option). Add pattern for success end, waring exit, error exit
- [ ] Add config option
- [ ] (Optional) Add unit tests for the new analysis tool's `Processor` if needed.
- [ ] Write documentation accordingly
- [ ] Add CI setting (https://github.com/sider/runners/blob/master/.circleci/config.yml)
- [ ] Discuss this Lint tool in this Issue
- [ ] Fix developer guide if needed (https://github.com/sider/runners#developer-guide)

**Comment by ybiquitous** [comment]
Doc: https://github.com/sider/sider-docs/pull/310
