### ISSUE TITLE
Support Sonar C#

### ISSUE THREAD

**Issue by gnakagaw** [sider/runners#712]
**Is your feature request related to a problem? Please describe.**
Support Sonar C# (https://github.com/SonarSource/sonar-dotnet)

**Describe the solution you'd like**
implement a new runner for Sonar C#

## Support Sonar C#

- Source code URL: https://github.com/SonarSource/sonar-dotnet
- Official Site/Documentation: https://www.sonarsource.com/products/codeanalyzers/sonarcsharp.html

## TODO

- [ ] Write smoke test(with some linter's Option). Add pattern for success end, waring exit, error exit
- [ ] Add config option
- [ ] (Optional) Add unit tests for the new analysis tool's `Processor` if needed.
- [ ] Write documentation accordingly
- [ ] Add CI setting (https://github.com/sider/runners/blob/master/.circleci/config.yml)
- [ ] Discuss this Lint tool in this Issue
- [ ] Fix developer guide if needed (https://github.com/sider/runners#developer-guide)

**Comment by gnakagaw** [comment]
I added a new base image to devon_rex repo because this is the first static analyser for .NET Core environment.
https://github.com/sider/devon_rex/pull/136

**Comment by gnakagaw** [comment]
Close. We decided to implement FxCop Analyzer at first. (#724 )
